// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import servicelib "github.com/eirikbell/slap/servicelib"

// LibraryService is an autogenerated mock type for the LibraryService type
type LibraryService struct {
	mock.Mock
}

// CollectPayment provides a mock function with given fields: _a0, _a1
func (_m *LibraryService) CollectPayment(_a0 int, _a1 int) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBook provides a mock function with given fields: _a0
func (_m *LibraryService) GetBook(_a0 string) *servicelib.Book {
	ret := _m.Called(_a0)

	var r0 *servicelib.Book
	if rf, ok := ret.Get(0).(func(string) *servicelib.Book); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicelib.Book)
		}
	}

	return r0
}

// GetCustomer provides a mock function with given fields: _a0
func (_m *LibraryService) GetCustomer(_a0 int) (*servicelib.Customer, error) {
	ret := _m.Called(_a0)

	var r0 *servicelib.Customer
	if rf, ok := ret.Get(0).(func(int) *servicelib.Customer); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servicelib.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLendsForCustomer provides a mock function with given fields: _a0
func (_m *LibraryService) GetLendsForCustomer(_a0 int) ([]*servicelib.Book, error) {
	ret := _m.Called(_a0)

	var r0 []*servicelib.Book
	if rf, ok := ret.Get(0).(func(int) []*servicelib.Book); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*servicelib.Book)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOldDbBooks provides a mock function with given fields:
func (_m *LibraryService) GetOldDbBooks() []*servicelib.Book {
	ret := _m.Called()

	var r0 []*servicelib.Book
	if rf, ok := ret.Get(0).(func() []*servicelib.Book); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*servicelib.Book)
		}
	}

	return r0
}

// SaveBook provides a mock function with given fields: _a0
func (_m *LibraryService) SaveBook(_a0 *servicelib.Book) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*servicelib.Book) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
