// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import magic "github.com/eirikbell/slap/magic"
import mock "github.com/stretchr/testify/mock"

// LibraryService is an autogenerated mock type for the LibraryService type
type LibraryService struct {
	mock.Mock
}

// CollectPayment provides a mock function with given fields: _a0, _a1
func (_m *LibraryService) CollectPayment(_a0 int, _a1 int) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBook provides a mock function with given fields: _a0
func (_m *LibraryService) GetBook(_a0 string) *magic.Book {
	ret := _m.Called(_a0)

	var r0 *magic.Book
	if rf, ok := ret.Get(0).(func(string) *magic.Book); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*magic.Book)
		}
	}

	return r0
}

// GetCustomer provides a mock function with given fields: _a0
func (_m *LibraryService) GetCustomer(_a0 int) (*magic.Customer, error) {
	ret := _m.Called(_a0)

	var r0 *magic.Customer
	if rf, ok := ret.Get(0).(func(int) *magic.Customer); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*magic.Customer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLendsForCustomer provides a mock function with given fields: _a0
func (_m *LibraryService) GetLendsForCustomer(_a0 int) ([]*magic.Book, error) {
	ret := _m.Called(_a0)

	var r0 []*magic.Book
	if rf, ok := ret.Get(0).(func(int) []*magic.Book); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*magic.Book)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOldDbBooks provides a mock function with given fields:
func (_m *LibraryService) GetOldDbBooks() []*magic.Book {
	ret := _m.Called()

	var r0 []*magic.Book
	if rf, ok := ret.Get(0).(func() []*magic.Book); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*magic.Book)
		}
	}

	return r0
}

// SaveBook provides a mock function with given fields: _a0
func (_m *LibraryService) SaveBook(_a0 *magic.Book) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*magic.Book) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
